baseURL = "https://MaxDragonheart.github.io/WebMap/"
languageCode = "it-it"
title = "WebMap"
enableRobotsTXT = true

[markup.goldmark.renderer]
unsafe = true  # consente HTML nei contenuti

[params]
siteName = "WebMap"
